language: node_js
node_js:
 - "10.5"

env:
  global:
    - CI=false

## Script to Install it
install:
 - npm install
  # Install any dependencies required for building your site here.
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install awscli

## Script to build it
script:
 - npm run build

deploy:
  
  # Branch to deploy (on means don't trigger unless)
  on:
    branch: master
  provider: s3

  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  # Name of s3 bucket
  bucket: s3-react-test-app

  #Don't delete after build
  skip_cleanup: true

  #Path to local dir for site
  local_dir: build

  # Set the cache-control header
  cache_control: "max-age=21600"

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

